export const weeksOf2 = [
  {
    week: 1,
    groups: [
      ["Himesh Patel", "Eliana Baird"],
      ["Tom Lowen", "Nasra Diini"],
      ["Cristofer Schaefer", "Christopher Barajas"],
      ["Deshawn Berry", "Sean Wolfe"],
      ["Imani Ortiz", "Anne Levy"],
      ["Orion Parker", "Gillian Wise"],
      ["Joy Lin", "Laurence Meah"],
      ["Mark Gilligan", "Delilah Acevedo"],
      ["Amiya Brennan", "Kallie Tanner"],
      ["Keenan Morris", "Moses Meadows"],
      ["Liz Kaufman", "Evelin Mullins"],
      ["Irfan Mohammed", "Tao Sharma"],
      ["Izabella Arias", "Nevaeh Booth"],
      ["Mohit Sharma", "James Perrett"],
      ["Joseph T", "Billy Hughes"],
      ["Siddharth Nair", "Kody Delacruz"],
      ["Tzu-Yun Lin", "Finnegan Norman"],
      ["Hamza Ibrahim", "Trevor Santiago"],
      ["Yadira Schwartz", "Jadon Neal"],
      ["Braxton Velez", "Jaydon Gilmore"],
      ["Dale Sloan", "Aryana Werner"],
      ["Mitchell Colson", "Marin Ellis"],
      ["Jay Gillespie", "Trenton Donovan"],
      ["Lizard Morrow", "Juweyriya Abdikadir"],
    ],
  },
  {
    week: 2,
    groups: [
      ["Tom Lowen", "Juweyriya Abdikadir"],
      ["Nevaeh Booth", "Amiya Brennan"],
      ["Joy Lin", "Anne Levy"],
      ["Yadira Schwartz", "Jay Gillespie"],
      ["Keenan Morris", "Delilah Acevedo"],
      ["Liz Kaufman", "Marin Ellis"],
      ["Irfan Mohammed", "Laurence Meah"],
      ["Braxton Velez", "Mitchell Colson"],
      ["Hamza Ibrahim", "Nasra Diini"],
      ["Eliana Baird", "James Perrett"],
      ["Tzu-Yun Lin", "Finnegan Norman"],
      ["Mark Gilligan", "Tao Sharma"],
      ["Dale Sloan", "Deshawn Berry"],
      ["Evelin Mullins", "Christopher Barajas"],
      ["Jaydon Gilmore", "Trenton Donovan"],
      ["Gillian Wise", "Mohit Sharma"],
      ["Sean Wolfe", "Kody Delacruz"],
      ["Aryana Werner", "Jadon Neal"],
      ["Himesh Patel", "Billy Hughes"],
      ["Cristofer Schaefer", "Joseph T"],
      ["Lizard Morrow", "Izabella Arias"],
      ["Siddharth Nair", "Orion Parker"],
      ["Imani Ortiz", "Moses Meadows"],
      ["Kallie Tanner", "Trevor Santiago"],
    ],
  },
  {
    week: 3,
    groups: [
      ["Eliana Baird", "Keenan Morris"],
      ["Mitchell Colson", "Delilah Acevedo"],
      ["Gillian Wise", "Sean Wolfe"],
      ["Cristofer Schaefer", "Siddharth Nair"],
      ["Laurence Meah", "Billy Hughes"],
      ["Marin Ellis", "Juweyriya Abdikadir"],
      ["Mohit Sharma", "Joseph T"],
      ["Deshawn Berry", "Mark Gilligan"],
      ["Kallie Tanner", "Jaydon Gilmore"],
      ["Tom Lowen", "Evelin Mullins"],
      ["Hamza Ibrahim", "Orion Parker"],
      ["Moses Meadows", "Nasra Diini"],
      ["Joy Lin", "Tao Sharma"],
      ["Aryana Werner", "Jay Gillespie"],
      ["Kody Delacruz", "Jadon Neal"],
      ["Lizard Morrow", "Imani Ortiz"],
      ["Nevaeh Booth", "Anne Levy"],
      ["James Perrett", "Braxton Velez"],
      ["Izabella Arias", "Irfan Mohammed"],
      ["Dale Sloan", "Amiya Brennan"],
      ["Liz Kaufman", "Himesh Patel"],
      ["Christopher Barajas", "Tzu-Yun Lin"],
      ["Trenton Donovan", "Trevor Santiago"],
      ["Finnegan Norman", "Yadira Schwartz"],
    ],
  },
  {
    week: 4,
    groups: [
      ["Cristofer Schaefer", "Marin Ellis"],
      ["Delilah Acevedo", "James Perrett"],
      ["Hamza Ibrahim", "Christopher Barajas"],
      ["Jadon Neal", "Joy Lin"],
      ["Siddharth Nair", "Tom Lowen"],
      ["Eliana Baird", "Gillian Wise"],
      ["Moses Meadows", "Himesh Patel"],
      ["Izabella Arias", "Deshawn Berry"],
      ["Tao Sharma", "Jaydon Gilmore"],
      ["Trevor Santiago", "Kallie Tanner"],
      ["Trenton Donovan", "Braxton Velez"],
      ["Irfan Mohammed", "Mark Gilligan"],
      ["Jay Gillespie", "Yadira Schwartz"],
      ["Anne Levy", "Joseph T"],
      ["Sean Wolfe", "Billy Hughes"],
      ["Evelin Mullins", "Imani Ortiz"],
      ["Liz Kaufman", "Nevaeh Booth"],
      ["Aryana Werner", "Amiya Brennan"],
      ["Orion Parker", "Keenan Morris"],
      ["Laurence Meah", "Finnegan Norman"],
      ["Mohit Sharma", "Kody Delacruz"],
      ["Tzu-Yun Lin", "Dale Sloan"],
      ["Mitchell Colson", "Juweyriya Abdikadir"],
      ["Lizard Morrow", "Nasra Diini"],
    ],
  },
  {
    week: 5,
    groups: [
      ["Dale Sloan", "Mark Gilligan"],
      ["Kody Delacruz", "Billy Hughes"],
      ["Marin Ellis", "Trevor Santiago"],
      ["Braxton Velez", "Anne Levy"],
      ["Tao Sharma", "Kallie Tanner"],
      ["Imani Ortiz", "Tzu-Yun Lin"],
      ["Trenton Donovan", "Deshawn Berry"],
      ["Tom Lowen", "Delilah Acevedo"],
      ["Laurence Meah", "Evelin Mullins"],
      ["Juweyriya Abdikadir", "Jay Gillespie"],
      ["Keenan Morris", "James Perrett"],
      ["Joy Lin", "Lizard Morrow"],
      ["Sean Wolfe", "Liz Kaufman"],
      ["Hamza Ibrahim", "Finnegan Norman"],
      ["Mitchell Colson", "Christopher Barajas"],
      ["Nasra Diini", "Nevaeh Booth"],
      ["Cristofer Schaefer", "Gillian Wise"],
      ["Moses Meadows", "Aryana Werner"],
      ["Irfan Mohammed", "Izabella Arias"],
      ["Eliana Baird", "Jaydon Gilmore"],
      ["Himesh Patel", "Yadira Schwartz"],
      ["Joseph T", "Siddharth Nair"],
      ["Jadon Neal", "Mohit Sharma"],
      ["Orion Parker", "Amiya Brennan"],
    ],
  },
  {
    week: 6,
    groups: [
      ["Keenan Morris", "Deshawn Berry"],
      ["Irfan Mohammed", "Mitchell Colson"],
      ["Himesh Patel", "Aryana Werner"],
      ["Kallie Tanner", "Evelin Mullins"],
      ["Joseph T", "Mohit Sharma"],
      ["Anne Levy", "Hamza Ibrahim"],
      ["James Perrett", "Orion Parker"],
      ["Gillian Wise", "Izabella Arias"],
      ["Cristofer Schaefer", "Finnegan Norman"],
      ["Tom Lowen", "Mark Gilligan"],
      ["Liz Kaufman", "Siddharth Nair"],
      ["Jadon Neal", "Tzu-Yun Lin"],
      ["Dale Sloan", "Kody Delacruz"],
      ["Imani Ortiz", "Trenton Donovan"],
      ["Joy Lin", "Juweyriya Abdikadir"],
      ["Trevor Santiago", "Billy Hughes"],
      ["Laurence Meah", "Jay Gillespie"],
      ["Tao Sharma", "Eliana Baird"],
      ["Braxton Velez", "Yadira Schwartz"],
      ["Moses Meadows", "Lizard Morrow"],
      ["Delilah Acevedo", "Sean Wolfe"],
      ["Nevaeh Booth", "Marin Ellis"],
      ["Amiya Brennan", "Nasra Diini"],
      ["Christopher Barajas", "Jaydon Gilmore"],
    ],
  },
  {
    week: 7,
    groups: [
      ["Jay Gillespie", "Imani Ortiz"],
      ["Lizard Morrow", "Mark Gilligan"],
      ["Nevaeh Booth", "Delilah Acevedo"],
      ["Billy Hughes", "Trenton Donovan"],
      ["Tom Lowen", "Laurence Meah"],
      ["Deshawn Berry", "Gillian Wise"],
      ["Juweyriya Abdikadir", "Siddharth Nair"],
      ["Kallie Tanner", "Jaydon Gilmore"],
      ["Izabella Arias", "Tao Sharma"],
      ["Irfan Mohammed", "Liz Kaufman"],
      ["Mohit Sharma", "Anne Levy"],
      ["Himesh Patel", "Kody Delacruz"],
      ["James Perrett", "Braxton Velez"],
      ["Mitchell Colson", "Orion Parker"],
      ["Yadira Schwartz", "Amiya Brennan"],
      ["Cristofer Schaefer", "Moses Meadows"],
      ["Keenan Morris", "Sean Wolfe"],
      ["Tzu-Yun Lin", "Finnegan Norman"],
      ["Jadon Neal", "Joseph T"],
      ["Evelin Mullins", "Christopher Barajas"],
      ["Nasra Diini", "Marin Ellis"],
      ["Aryana Werner", "Trevor Santiago"],
      ["Hamza Ibrahim", "Eliana Baird"],
      ["Joy Lin", "Dale Sloan"],
    ],
  },
  {
    week: 8,
    groups: [
      ["Anne Levy", "Lizard Morrow"],
      ["Braxton Velez", "Nevaeh Booth"],
      ["Laurence Meah", "Joy Lin"],
      ["Yadira Schwartz", "Mohit Sharma"],
      ["Nasra Diini", "Jaydon Gilmore"],
      ["Cristofer Schaefer", "Amiya Brennan"],
      ["Deshawn Berry", "Kallie Tanner"],
      ["James Perrett", "Tzu-Yun Lin"],
      ["Hamza Ibrahim", "Mark Gilligan"],
      ["Juweyriya Abdikadir", "Mitchell Colson"],
      ["Moses Meadows", "Gillian Wise"],
      ["Finnegan Norman", "Irfan Mohammed"],
      ["Orion Parker", "Tao Sharma"],
      ["Trenton Donovan", "Dale Sloan"],
      ["Aryana Werner", "Evelin Mullins"],
      ["Eliana Baird", "Jay Gillespie"],
      ["Izabella Arias", "Kody Delacruz"],
      ["Joseph T", "Christopher Barajas"],
      ["Siddharth Nair", "Liz Kaufman"],
      ["Marin Ellis", "Himesh Patel"],
      ["Trevor Santiago", "Keenan Morris"],
      ["Delilah Acevedo", "Sean Wolfe"],
      ["Jadon Neal", "Billy Hughes"],
      ["Imani Ortiz", "Tom Lowen"],
    ],
  },
  {
    week: 9,
    groups: [
      ["Delilah Acevedo", "Kallie Tanner"],
      ["Billy Hughes", "Christopher Barajas"],
      ["Eliana Baird", "Evelin Mullins"],
      ["Sean Wolfe", "Marin Ellis"],
      ["Cristofer Schaefer", "Lizard Morrow"],
      ["Mark Gilligan", "Joseph T"],
      ["Trenton Donovan", "Nasra Diini"],
      ["Anne Levy", "Tzu-Yun Lin"],
      ["Imani Ortiz", "Trevor Santiago"],
      ["Himesh Patel", "Amiya Brennan"],
      ["Braxton Velez", "Laurence Meah"],
      ["Keenan Morris", "James Perrett"],
      ["Siddharth Nair", "Irfan Mohammed"],
      ["Kody Delacruz", "Yadira Schwartz"],
      ["Gillian Wise", "Deshawn Berry"],
      ["Mitchell Colson", "Izabella Arias"],
      ["Nevaeh Booth", "Dale Sloan"],
      ["Finnegan Norman", "Joy Lin"],
      ["Jay Gillespie", "Orion Parker"],
      ["Aryana Werner", "Juweyriya Abdikadir"],
      ["Tom Lowen", "Moses Meadows"],
      ["Tao Sharma", "Jaydon Gilmore"],
      ["Hamza Ibrahim", "Liz Kaufman"],
      ["Mohit Sharma", "Jadon Neal"],
    ],
  },
  {
    week: 10,
    groups: [
      ["Yadira Schwartz", "James Perrett"],
      ["Juweyriya Abdikadir", "Gillian Wise"],
      ["Orion Parker", "Nevaeh Booth"],
      ["Dale Sloan", "Kody Delacruz"],
      ["Joseph T", "Cristofer Schaefer"],
      ["Delilah Acevedo", "Lizard Morrow"],
      ["Sean Wolfe", "Tzu-Yun Lin"],
      ["Kallie Tanner", "Siddharth Nair"],
      ["Aryana Werner", "Nasra Diini"],
      ["Billy Hughes", "Jay Gillespie"],
      ["Jaydon Gilmore", "Amiya Brennan"],
      ["Imani Ortiz", "Moses Meadows"],
      ["Eliana Baird", "Izabella Arias"],
      ["Trevor Santiago", "Anne Levy"],
      ["Hamza Ibrahim", "Jadon Neal"],
      ["Tao Sharma", "Trenton Donovan"],
      ["Christopher Barajas", "Irfan Mohammed"],
      ["Liz Kaufman", "Braxton Velez"],
      ["Tom Lowen", "Keenan Morris"],
      ["Evelin Mullins", "Deshawn Berry"],
      ["Mitchell Colson", "Mohit Sharma"],
      ["Marin Ellis", "Mark Gilligan"],
      ["Laurence Meah", "Finnegan Norman"],
      ["Joy Lin", "Himesh Patel"],
    ],
  },
  {
    week: 11,
    groups: [
      ["Kallie Tanner", "Marin Ellis"],
      ["Aryana Werner", "James Perrett"],
      ["Mohit Sharma", "Tzu-Yun Lin"],
      ["Deshawn Berry", "Nevaeh Booth"],
      ["Liz Kaufman", "Anne Levy"],
      ["Braxton Velez", "Hamza Ibrahim"],
      ["Finnegan Norman", "Keenan Morris"],
      ["Jay Gillespie", "Gillian Wise"],
      ["Juweyriya Abdikadir", "Christopher Barajas"],
      ["Cristofer Schaefer", "Mitchell Colson"],
      ["Sean Wolfe", "Yadira Schwartz"],
      ["Delilah Acevedo", "Evelin Mullins"],
      ["Joseph T", "Jaydon Gilmore"],
      ["Jadon Neal", "Imani Ortiz"],
      ["Tom Lowen", "Amiya Brennan"],
      ["Himesh Patel", "Siddharth Nair"],
      ["Izabella Arias", "Irfan Mohammed"],
      ["Eliana Baird", "Billy Hughes"],
      ["Trevor Santiago", "Laurence Meah"],
      ["Joy Lin", "Kody Delacruz"],
      ["Lizard Morrow", "Orion Parker"],
      ["Tao Sharma", "Mark Gilligan"],
      ["Moses Meadows", "Dale Sloan"],
      ["Trenton Donovan", "Nasra Diini"],
    ],
  },
  {
    week: 12,
    groups: [
      ["Irfan Mohammed", "Finnegan Norman"],
      ["Mitchell Colson", "Cristofer Schaefer"],
      ["Hamza Ibrahim", "Nevaeh Booth"],
      ["Joy Lin", "Billy Hughes"],
      ["Yadira Schwartz", "Amiya Brennan"],
      ["Christopher Barajas", "Tzu-Yun Lin"],
      ["Evelin Mullins", "Mohit Sharma"],
      ["James Perrett", "Liz Kaufman"],
      ["Braxton Velez", "Anne Levy"],
      ["Gillian Wise", "Aryana Werner"],
      ["Kallie Tanner", "Joseph T"],
      ["Laurence Meah", "Nasra Diini"],
      ["Trevor Santiago", "Mark Gilligan"],
      ["Marin Ellis", "Kody Delacruz"],
      ["Jay Gillespie", "Izabella Arias"],
      ["Sean Wolfe", "Imani Ortiz"],
      ["Tao Sharma", "Keenan Morris"],
      ["Delilah Acevedo", "Siddharth Nair"],
      ["Eliana Baird", "Moses Meadows"],
      ["Deshawn Berry", "Jadon Neal"],
      ["Trenton Donovan", "Orion Parker"],
      ["Jaydon Gilmore", "Dale Sloan"],
      ["Tom Lowen", "Juweyriya Abdikadir"],
      ["Lizard Morrow", "Himesh Patel"],
    ],
  },
];
